### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by SalathielGenese** [tambapps/marcel#1]
https://twitter.com/SalathielGenese/

**Comment by tambapps** [comment]
I don't understand, what is the issue here?

**Comment by SalathielGenese** [comment]
You presented Marcel during an online event, and I reached out to express my interest in the project. Namely, to get involved. Namely I didn't had other means to reach out.

**Comment by tambapps** [comment]
My email is [tambapps@gmail.com](mailto:tambapps@gmail.com and my twitter account is https://twitter.com/tambapps
